language: node_js
node_js: 8.11.1
script:
  - npm install
  - npm run build
  - git describe
deploy:
  provider: releases
  api_key:
    secure: fXmzPeMwuJkSXpmVe2P7nYfVdsRWhWzfrYR3g3rXSz2oQFCCSR1M/cWly2NQFfH/P48UoszLRqVY9lSGqzQPFFXPuQzaeXRhA/cVctnEWPPeesyH2Au+8CQe91lkFcGFTUCBQUwx7ePjTw4MB4QNc1uI1tIh65i+e8xrMYpx/Sc8Bi8w5RPiQ1YXEHoc+lB9AoAagCVmXODlAbp0Cq79JsYmz106NflcBFeQDJKUtvbsI1SsLDSR4GBsnWZ8w2epSoGpXkXe1iic7UYoUtavVVEVxh0lU39PBzuZ3Lh5YyGYXRnibsa+LdgB/PpTMeRyvgOug1P7S2nksOvshwKBTNAwXUGEVu92lx6AHJMR1Hwmzznzn/Bf86pRRzP5HguEVx7wyY7Hb9XElmBtS85oPabvFrE4jEU8Qu4xcv1xNW3WtpY6BniEZcBr63pMoYqwV2VdWfJ9341RAnY9IFDUkYAzdu4IqJVGkr2frya9iXTkc3jGdc/LgGv2tNkkjvE+24rw9wURGJTwR21snX78vWFoZBGeZE3nMFB/SCw8UQjta4MstcmHOAoLA9PLCvSANOF69t+X40rhXZe1XIjhrulvj55HjvIZQNiPrExiZAVNZ/ykz2PopTVvi5erXtWzDuKZgDBzEue6YF6r7RdcHvqoDb32udIkwU5v40l8gB4=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: fortinet/aws-lambda-logstorage
    tags: true
    branch: master
